### ISSUE TITLE
eslint configuration can supports v9

### ISSUE THREAD

**Issue by Mutter45** [EricWXY/vite-ts-lib-starter#1]
With the release of eslint v9, more and more projects have supported v9, and support for new project templates should be better

**Comment by EricWXY** [comment]
Okay, I will consider upgrading.

**Comment by Mutter45** [comment]
thanks for your reply

**Comment by EricWXY** [comment]
We are all Chinese, why do we communicate in English...

**Comment by Mutter45** [comment]
哈哈，确实呢，以为用英文，可以让更多的人了解呢，在社区感觉用英文会得到更好的回复

**Comment by EricWXY** [comment]
哈哈，最近在写别的东西，写完就来改这个模板

**Comment by EricWXY** [comment]
https://github.com/EricWXY/vite-ts-lib-starter/commit/fd68022e504bcc2fe6c78182358829573ebf86c2
